### ISSUE TITLE
响应式设计

### ISSUE THREAD

**Issue by beilo** [beilo/blog#9]
## 一、核心知识点总结

响应式设计的本质是使网站能够适应不同设备的屏幕大小，提供最佳用户体验。实现这一目标需要掌握三大核心技术和多种辅助技巧。

#### 1.1 CSS媒体查询（Media Queries）
- **基础用法**：根据屏幕宽度设置不同样式
```css
/* 平板设备 */
@media (min-width: 768px) and (max-width: 1024px) {
  body { font-size: 18px; }
}

/* 桌面设备 */
@media (min-width: 1025px) {
  body { font-size: 20px; }
}
```

- **高级用法**：结合设备方向和分辨率
```css
/* 高分辨率屏幕 */
@media (min-resolution: 2dppx) {
  body { background-image: url('background-hd.jpg'); }
}

/* 竖屏设备 */
@media (orientation: portrait) {
  body { padding: 10px; }
}
```

#### 1.2 弹性布局（Flexbox）
- **适用场景**：一维布局（水平或垂直排列）
- **核心属性**：display: flex, justify-content, align-items
```css
.container {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
```

#### 1.3 网格布局（Grid）
- **适用场景**：二维布局（行列结构）
- **核心属性**：display: grid, grid-template-columns, grid-template-rows
```css
.grid-container {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(2, 100px);
  gap: 10px;
}
```

#### 2.1 视口单位（vw/vh）
```css
.container {
  width: 80vw;  /* 视口宽度的80% */
  height: 80vh; /* 视口高度的80% */
}
```

#### 2.2 响应式图片处理
```html
<img src="image.jpg" srcset="image.jpg 1x, image-2x.jpg 2x" alt="响应式图片">
```

#### 2.3 CSS变量
```css
:root {
  --main-color: #e60027;
  --font-size: 16px;
}

body {
  color: var(--main-color);
  font-size: var(--font-size);
}
```

#### 3.1 图片懒加载
```javascript
document.addEventListener('scroll', () => {
  const images = document.querySelectorAll('img[data-src]');
  images.forEach(img => {
    if (img.getBoundingClientRect().top < window.innerHeight) {
      img.src = img.dataset.src;
      img.removeAttribute('data-src');
    }
  });
});
```

#### 3.2 WebP图片格式
```html
<picture>
  <source srcset="image.webp" type="image/webp">
  <source srcset="image.jpg" type="image/jpeg">
  <img src="image.jpg" alt="WebP图片">
</picture>
```
